import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Najmus Sakib Rashid",
//     description: "Generated by create next app",
// };

export const metadata: Metadata = {
    title: "Najmus Sakib Rashid - Software Engineer & Developer",
    description:
        "Personal portfolio website of Najmus Sakib Rashid, showcasing skills, projects, and professional experience in software development.",
    openGraph: {
        title: "Najmus Sakib Rashid - Software Engineer & Developer",
        description:
            "Personal portfolio website showcasing skills, projects, and professional experience in software development.",
        url: "https://najmus-sakib-rashid-99.vercel.app/",
        siteName: "Najmus Sakib Rashid Portfolio",
        images: [
            {
                url: "https://najmus-sakib-rashid-99.vercel.app/website-preview-image.svg",
                width: 1200,
                height: 630,
            },
        ],
        locale: "en_US",
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: "Najmus Sakib Rashid - Software Engineer & Developer",
        description:
            "Personal portfolio website showcasing skills, projects, and professional experience in software development.",
        images: [
            "https://najmus-sakib-rashid-99.vercel.app/website-preview-image.svg",
        ],
    },
};

import PrelineScriptWrapper from "./components/PrelineScriptWrapper";
import Navbar from "./components/Navbar.jsx";
import Footer from "./components/Footer.jsx";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar />
                {children}
                <Footer />
            </body>
            <PrelineScriptWrapper />
        </html>
    );
}
